In [3]:
import pandas as pd

data = {
    "height": [165, 172, None, 180, 158, 175],
    "weight": [55, 70, 65, 80, 50, 68],
    "age": [25, 30, 28, 35, 22, 29],
    "gender": ["F", "M", "M", "M", "F", "M"],
}

df = pd.DataFrame(data)

In [4]:
df.head()

   height  weight  age gender
0   165.0      55   25      F
1   172.0      70   30      M
2     NaN      65   28      M
3   180.0      80   35      M
4   158.0      50   22      F

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  5 non-null      float64
 1   weight  6 non-null      int64
 2   age     6 non-null      int64
 3   gender  6 non-null      str
dtypes: float64(1), int64(2), str(1)
memory usage: 330.0 bytes

In [ ]:
df.describe()
# 캐시 지우는 것보다 >Developer: Reload Window해서

           height     weight        age
count    5.000000   6.000000   6.000000
mean   170.000000  64.666667  28.166667
std      8.631338  10.801234   4.445972
min    158.000000  50.000000  22.000000
25%    165.000000  57.500000  25.750000
50%    172.000000  66.500000  28.500000
75%    175.000000  69.500000  29.750000
max    180.000000  80.000000  35.000000

In [ ]:
df.isnull().sum() # 결측치 갯수

height    1
weight    0
age       0
gender    0
dtype: int64

In [ ]:
# 결측치가 있는 행 제거 : .dropna()
df.dropna()

   height  weight  age gender
0   165.0      55   25      F
1   172.0      70   30      M
3   180.0      80   35      M
4   158.0      50   22      F
5   175.0      68   29      M

In [10]:
# 미리보기가 마음에 든다면,
df2 = df.dropna()
df2

   height  weight  age gender
0   165.0      55   25      F
1   172.0      70   30      M
3   180.0      80   35      M
4   158.0      50   22      F
5   175.0      68   29      M

In [ ]:
# 결측치 채우기 : .fillna()
# 숫자형들을 평균값으로 채우기 - 키(height)
df['height'].fillna(df['height'].mean())

0    165.0
1    172.0
2    170.0
3    180.0
4    158.0
5    175.0
Name: height, dtype: float64

In [ ]:
df3 = df.copy() # 원본데이터는 왠만하면 보관하고, 카피본을 만드는게 나음
df3['height'] = df['height'].fillna(df['height'].mean())
df3

   height  weight  age gender
0   165.0      55   25      F
1   172.0      70   30      M
2   170.0      65   28      M
3   180.0      80   35      M
4   158.0      50   22      F
5   175.0      68   29      M

In [ ]:
# 결측치 채우기 : .fillna()
# 이번에는 범주형들을 최빈값으로 채우기 - 성별(gender)
df['gender'].mode() # 아~ 최빈값은 M 남자구나~!
type(df['gender'].mode()) # pandas.Series구나~ (파이썬에서 리스트가 판다스에선 1차형 시리즈라고 함ㅇㅇ) 엥...?왜...?
df['gender'].mode()[0] # 아 지금 다시보니까 0  M이였네?
type(df['gender'].mode()[0]) # M이 str이였구나...!

str

## 인코딩(Encoding)
: 문자 데이터를 숫자로 바꾸는 과정

- 레이블 인코딩 (Label Encoding)
  : 값에 숫자를 직접 매긴다 ex. 월화수목금토일
- 원-핫 인코딩 (One-hot Encoding)
  : 순서가 없고 참/거짓만 있는 경우 ex. 남녀

In [24]:
# 레이블 인코딩
df['gender_num'] = df['gender'].map({'F':0, 'M':1})
df

   height  weight  age gender  gender_num
0   165.0      55   25      F           0
1   172.0      70   30      M           1
2     NaN      65   28      M           1
3   180.0      80   35      M           1
4   158.0      50   22      F           0
5   175.0      68   29      M           1

In [25]:
# 원-핫 인코딩
df_encoded = pd.get_dummies(df, columns=['gender']) # .get_dummies() 정말 많이 씁니다
df_encoded

   height  weight  age  gender_num  gender_F  gender_M
0   165.0      55   25           0      True     False
1   172.0      70   30           1     False      True
2     NaN      65   28           1     False      True
3   180.0      80   35           1     False      True
4   158.0      50   22           0      True     False
5   175.0      68   29           1     False      True

## 스케일링
: 숫자 값의 범위를 조정
ex. 나이 -> 20~70, 연봉 -> 30,000,000 이 둘의 숫자차이가 너무 크다

- MinMaxScaler
: 사이킷런 안에 있는 함수 / 값을 0~1사이 범위로 바꿔준다
- StandardScaler
: 사이킷런 안에 있는 함수 / 평균이 0, 표준편차가 1이 되도록 조정 (=정규분포..?)

In [ ]:
# uv pip list를 보면 skitlearn이 없네요? python.org 홈페이지 - PyPI(외부라이브러리 확인)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # 붕어빵.. 이 객체에 모든 MinMaxScaler의 기능을 넣어요?
df[['height_scaled']] = scaler.fit_transform(df[['height']])
df
# 키가 젤 작은 애가 0.000 젤 큰 애가 1.000

   height  weight  age gender  gender_num  height_scaled
0   165.0      55   25      F           0       0.318182
1   172.0      70   30      M           1       0.636364
2     NaN      65   28      M           1            NaN
3   180.0      80   35      M           1       1.000000
4   158.0      50   22      F           0       0.000000
5   175.0      68   29      M           1       0.772727

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['height_standard']] = scaler.fit_transform(df[['height']])
df

   height  weight  age gender  gender_num  height_scaled  height_standard
0   165.0      55   25      F           0       0.318182        -0.647660
1   172.0      70   30      M           1       0.636364         0.259064
2     NaN      65   28      M           1            NaN              NaN
3   180.0      80   35      M           1       1.000000         1.295319
4   158.0      50   22      F           0       0.000000        -1.554383
5   175.0      68   29      M           1       0.772727         0.647660